<a href="https://colab.research.google.com/github/swflora/B.D.A/blob/main/%5B%ED%95%84%EC%88%98%EA%B3%BC%EC%A0%9C2%5D240316_%EB%8D%B0%EC%9D%B4%ED%84%B0%EB%B6%84%EC%84%9D_%ED%86%B5%EA%B3%84_pandas%EA%B8%B0%EC%B4%88%EB%AC%B8%EB%B2%95.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 필수과제2
- if, for를 가지고 만들어 주세요!
- pclass ,남성 여성까지 나눠서 확률 컬럼 만들기!
- pclass 1,2,3 성별 남,여
- 1, 남
- 1, 여... 3,남 3,여 생존확률

# 남성의 생존확률 구하기

In [2]:
import seaborn as sns
tt = sns.load_dataset('titanic')

tt

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [20]:
# 클래스 별 생존 확률
print(tt.query("""pclass == 3""").shape[0])
print(tt.query("""pclass == 2""").shape[0])
print(tt.query("""pclass == 1""").shape[0])

491
184
216

In [15]:
# 클래스 별로 생존 남성의 수 구하기
tt['pclass_prob'] = 0

for i in range(len(tt)):
    if tt.loc[i]['pclass'] == 3 and tt.loc[i]['sex'] == 'male':
        tt['pclass_prob'].loc[i] = tt.loc[i]['survived'].sum() / 491
    elif tt.loc[i]['pclass'] == 2 and tt.loc[i]['sex'] == 'male':
        tt['pclass_prob'].loc[i] = tt.loc[i]['survived'].sum() / 184
    elif tt.loc[i]['pclass'] == 1 and tt.loc[i]['sex'] == 'male':
        tt['pclass_prob'].loc[i] = tt.loc[i]['survived'].sum() / 216

for i in range(len(tt)):
    if tt.loc[i]['pclass'] == 3 and tt.loc[i]['sex'] == 'female':
        tt['pclass_prob'].loc[i] = tt.loc[i]['survived'].sum() / 491
    elif tt.loc[i]['pclass'] == 2 and tt.loc[i]['sex'] == 'female':
        tt['pclass_prob'].loc[i] = tt.loc[i]['survived'].sum() / 184
    elif tt.loc[i]['pclass'] == 1 and tt.loc[i]['sex'] == 'female':
        tt['pclass_prob'].loc[i] = tt.loc[i]['survived'].sum() / 216

<ipython-input-15-69873494009b>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tt['pclass_prob'].loc[i] = tt.loc[i]['survived'].sum() / 491
<ipython-input-15-69873494009b>:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tt['pclass_prob'].loc[i] = tt.loc[i]['survived'].sum() / 216
<ipython-input-15-69873494009b>:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tt['pclass_prob'].loc[i] = tt.loc[i]['survived'].sum() / 184

In [19]:
tt[['survived','pclass','pclass_prob']]

     survived  pclass  pclass_prob
0           0       3     0.000000
1           1       1     0.004630
2           1       3     0.002037
3           1       1     0.004630
4           0       3     0.000000
..        ...     ...          ...
886         0       2     0.000000
887         1       1     0.004630
888         0       3     0.000000
889         1       1     0.004630
890         0       3     0.000000

[891 rows x 3 columns]